[package]
name = "raytrace"
version = "0.1.0"
authors = ["cai-lw <cai_lw@126.com>"]

[dependencies]
gtk = "0.3.0"
gdk-pixbuf = "0.3.0"
cgmath = "0.16.0"
palette = "0.2.1"
rand = "0.4.2"
approx = "0.1.1"
noisy_float = "0.1.4"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_yaml = "0.7.3"